apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: earthly

resources:
- namespace.yaml
- https://raw.githubusercontent.com/earthly/ci-examples/05a76b1/kubernetes/remote-buildkitd/buildkit.yaml

patches:
- patch: |-
    - op: remove
      path: /spec/sessionAffinity
    - op: remove
      path: /spec/sessionAffinityConfig
  target:
    kind: Service
    name: earthly-buildkitd
- patch: |-
    - op: replace
      path: /kind
      value: DaemonSet
    - op: remove
      path: /spec/replicas
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        limits:
          memory: 2Gi
        requests:
          cpu: 1m
          memory: 2Gi
  target:
    kind: Deployment
    name: earthly-buildkitd

images:
- name: earthly/buildkitd
  newTag: v0.8.9
