apiVersion: v1
kind: ConfigMap
metadata:
  name: earthly-client-config
  namespace: earthly
data:
  config.yml: |-
    global:
      tlsca: /etc/ca.pem
      tlscert: /etc/cert.pem
      tlskey: /etc/key.pem
---
apiVersion: batch/v1
kind: Job
metadata:
  name: earthly-go-part6
  namespace: earthly
spec:
  template:
    metadata:
      labels:
        job: earthly
    spec:
      containers:
      - image: earthly/earthly:v0.8.15
        name: earthly-go-part6
        args:
        - -P
        - --ci
        - github.com/earthly/earthly/examples/tutorial/go/part6:main+integration-tests
        env:
        - name: BUILDKIT_HOST
          value: tcp://earthly-buildkitd:8372
        volumeMounts:
        - name: earthly-client-config
          mountPath: /etc/.earthly
        - name: earthly-client-tls-certs
          mountPath: /etc/cert.pem
          subPath: tls.crt
          readOnly: true
        - name: earthly-client-tls-certs
          mountPath: /etc/key.pem
          subPath: tls.key
          readOnly: true
        - name: earthly-client-tls-certs
          mountPath: /etc/ca.pem
          subPath: ca.crt
          readOnly: true
      volumes:
      - name: earthly-client-config
        configMap:
          name: earthly-client-config
      - name: earthly-client-tls-certs
        secret:
          secretName: earthly-client-tls-certs
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: earthly-java-part6
  namespace: earthly
spec:
  template:
    metadata:
      labels:
        job: earthly
    spec:
      containers:
      - image: earthly/earthly:v0.8.15
        name: earthly-java-part6
        args:
        - -P
        - --ci
        - github.com/earthly/earthly/examples/tutorial/java/part6:main+integration-tests
        env:
        - name: BUILDKIT_HOST
          value: tcp://earthly-buildkitd:8372
        volumeMounts:
        - name: earthly-client-config
          mountPath: /etc/.earthly
        - name: earthly-client-tls-certs
          mountPath: /etc/cert.pem
          subPath: tls.crt
          readOnly: true
        - name: earthly-client-tls-certs
          mountPath: /etc/key.pem
          subPath: tls.key
          readOnly: true
        - name: earthly-client-tls-certs
          mountPath: /etc/ca.pem
          subPath: ca.crt
          readOnly: true
      volumes:
      - name: earthly-client-config
        configMap:
          name: earthly-client-config
      - name: earthly-client-tls-certs
        secret:
          secretName: earthly-client-tls-certs
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: earthly-js-part6
  namespace: earthly
spec:
  template:
    metadata:
      labels:
        job: earthly
    spec:
      containers:
      - image: earthly/earthly:v0.8.15
        name: earthly-js-part6
        args:
        - -P
        - --ci
        - github.com/earthly/earthly/examples/tutorial/js/part6:main+integration-tests
        env:
        - name: BUILDKIT_HOST
          value: tcp://earthly-buildkitd:8372
        volumeMounts:
        - name: earthly-client-config
          mountPath: /etc/.earthly
        - name: earthly-client-tls-certs
          mountPath: /etc/cert.pem
          subPath: tls.crt
          readOnly: true
        - name: earthly-client-tls-certs
          mountPath: /etc/key.pem
          subPath: tls.key
          readOnly: true
        - name: earthly-client-tls-certs
          mountPath: /etc/ca.pem
          subPath: ca.crt
          readOnly: true
      volumes:
      - name: earthly-client-config
        configMap:
          name: earthly-client-config
      - name: earthly-client-tls-certs
        secret:
          secretName: earthly-client-tls-certs
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: earthly-python-part6
  namespace: earthly
spec:
  template:
    metadata:
      labels:
        job: earthly
    spec:
      containers:
      - image: earthly/earthly:v0.8.15
        name: earthly-python-part6
        args:
        - -P
        - --ci
        - github.com/zakame/earthly/examples/tutorial/python/part6:fix-tutorial-python-part6-psycopg+integration-tests
        env:
        - name: BUILDKIT_HOST
          value: tcp://earthly-buildkitd:8372
        volumeMounts:
        - name: earthly-client-config
          mountPath: /etc/.earthly
        - name: earthly-client-tls-certs
          mountPath: /etc/cert.pem
          subPath: tls.crt
          readOnly: true
        - name: earthly-client-tls-certs
          mountPath: /etc/key.pem
          subPath: tls.key
          readOnly: true
        - name: earthly-client-tls-certs
          mountPath: /etc/ca.pem
          subPath: ca.crt
          readOnly: true
      volumes:
      - name: earthly-client-config
        configMap:
          name: earthly-client-config
      - name: earthly-client-tls-certs
        secret:
          secretName: earthly-client-tls-certs
      restartPolicy: Never
