apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- pki.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "true"
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
      - mountPath: /tmp/earthly
        name: buildkitd-temp
      - name: earthly-buildkitd-tls-certs
        mountPath: /etc/cert.pem
        subPath: tls.crt
        readOnly: true
      - name: earthly-buildkitd-tls-certs
        mountPath: /etc/key.pem
        subPath: tls.key
        readOnly: true
      - name: earthly-buildkitd-tls-certs
        mountPath: /etc/ca.pem
        subPath: ca.crt
        readOnly: true
    - op: add
      path: /spec/template/spec/volumes
      value:
      - name: buildkitd-temp
        emptyDir: {}
      - name: earthly-buildkitd-tls-certs
        secret:
          secretName: earthly-buildkitd-tls-certs
  target:
    kind: Deployment
    name: earthly-buildkitd
